console.log("Hello, how are you?")
console.log("Hi! I'm fine. how are you?")
console.log("Fine thanks")
console.log("Can you please install the university library for me?")
console.log("Of course, you will leave this building and turn left")
console.log("thank you, what year are you in?")
console.log("I study in the 1st year, how about you?")
console.log("I study in the 3rd year.")
console.log("Yes good what is your name")
console.log("My name is Asilbek, what is your name?")
console.log("my name is Bahram")
console.log("It's nice to meet you")
console.log("I'm happy too")
console.log("Can we meet again next time?")
console.log("of course")
console.log("when will we meet?")
console.log("we can meet tomorrow at 9 o'clock in the university library if you have time")
console.log("we will meet tomorrow at 9 o'clock in the university library")
console.log("see you tomorrow")
console.log("Good bye")